### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by Ajita24** [tendermint/network_testing#1]
Hello
I am not able to get the mintnet repository. Everywhere it is stated that it is deprecated. Where I can get the code for mintnet.

**Comment by zramsay** [comment]
https://github.com/tendermint/tools ; `mintnet` was replaced with `mintnet-kubernetes`

**Comment by melekes** [comment]
Please check out https://blog.cosmos.network/get-your-cryptocurrency-up-and-running-in-10-minutes-9ae4c703eb1c for instructions. We also have Ansible scripts to deploy onto raw Linux machines.
